import { test, expect, type BrowserContext } from "@playwright/test";
import { Pool } from "pg";
import { randomUUID, createHmac } from "node:crypto";
const url=process.env.DATABASE_URL??"";
if(!url.includes("pawplan_records_check")||!url.includes("127.0.0.1"))throw new Error("Requires isolated pawplan_records_check database");
const pool=new Pool({connectionString:url});
let workspaceId:string,taskId:string;
const day=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Shanghai",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const longTitle="Gao：会前问题与算力比较——整理多篇文献中模型输入、计算成本与真实实验之间的区别，以及需要继续向老师确认的问题";
test.beforeEach(async({context,page})=>{
 await page.route("**/api/onboarding",route=>route.fulfill({json:{completedCount:4,totalCount:4,nextStep:null,steps:[]}}));
 workspaceId=randomUUID();taskId=randomUUID();const planId=randomUUID();
 await pool.query("insert into workspaces(id,name,password_hash) values($1,$2,'test')",[workspaceId,`records-${workspaceId}`]);
 await pool.query("insert into plans(id,workspace_id,title,start_date,end_date,status,baseline_snapshot) values($1,$2,'验收计划',$3,'2036-12-31','active','{}')",[planId,workspaceId,day()]);
 await pool.query("insert into tasks(id,workspace_id,plan_id,title,date,day_segment,scheduled_start,scheduled_end,estimated_minutes) values($1,$2,$3,$4,$5,'morning',$6,$7,30)",[taskId,workspaceId,planId,longTitle,`${day()}T00:00:00+08:00`,`${day()}T00:00:00+08:00`,`${day()}T00:30:00+08:00`]);
 await pool.query("insert into time_blocks(workspace_id,title,kind,starts_at,ends_at) values($1,'MATH 3700 · Big Data Computing','course',$2,$3)",[workspaceId,`${day()}T14:30:00+08:00`,`${day()}T15:45:00+08:00`]);
 const value=`${workspaceId}.${createHmac('sha256','test-secret').update(workspaceId).digest('base64url')}`;
 await context.addCookies([{name:"daily_progress_workspace",value,domain:"127.0.0.1",path:"/",httpOnly:true,sameSite:"Lax"}]);
});
test.afterEach(async()=>{await pool.query("delete from workspaces where id=$1",[workspaceId]);});
test.afterAll(async()=>{await pool.end();});

test("Today groups unfinished tasks and explains timeline states without inferring activity", async ({page,isMobile},info) => {
 const planId=(await pool.query('select plan_id from tasks where id=$1',[taskId])).rows[0].plan_id;
 const activeId=randomUUID(),doneId=randomUUID(),eveningId=randomUUID();
 for(const [id,title,segment,status,start,end,movable] of [
  [activeId,'下午阅读','afternoon','todo','12:00','13:00',false],
  [doneId,'已完成的晚间任务','evening','done',null,null,true],
  [eveningId,'晚间整理','evening','todo',null,null,true],
 ] as const) await pool.query('insert into tasks(id,workspace_id,plan_id,title,date,day_segment,status,scheduled_start,scheduled_end,movable,estimated_minutes) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,30)',[id,workspaceId,planId,title,`${day()}T00:00:00+08:00`,segment,status,start?`${day()}T${start}:00+08:00`:null,end?`${day()}T${end}:00+08:00`:null,movable]);
 await pool.query("insert into time_blocks(workspace_id,title,kind,starts_at,ends_at) values($1,'重叠会议','meeting',$2,$3)",[workspaceId,`${day()}T12:30:00+08:00`,`${day()}T13:15:00+08:00`]);
 await pool.query("insert into time_blocks(workspace_id,title,kind,starts_at,ends_at) values($1,'午休','recovery',$2,$3)",[workspaceId,`${day()}T01:30:00+08:00`,`${day()}T02:00:00+08:00`]);
 await pool.query("insert into actual_records(workspace_id,task_id,title,starts_at,ends_at) values($1,$2,'已做完的整理',$3,$4)",[workspaceId,doneId,`${day()}T00:40:00+08:00`,`${day()}T01:00:00+08:00`]);
 await page.clock.install({time:new Date(`${day()}T12:45:00+08:00`)});
 await page.goto('/today');
 if(isMobile) await page.setViewportSize({width:320,height:740});
 const groups=page.locator('.paw-today-task-group');
 await expect(groups.locator('h3')).toHaveText(['上午','下午','晚上','已完成']);
 const taskIds=()=>page.locator('.paw-task-list [data-task-id]').evaluateAll(nodes=>nodes.map(node=>node.getAttribute('data-task-id')));
 await expect.poll(taskIds).toEqual([taskId,activeId,eveningId,doneId]);
 await expect(page.locator('.paw-today-metrics')).toContainText('已完成1/4');
 await expect(page.getByText('向下越做越轻',{exact:true})).toHaveCount(0);
 await expect(page.getByText('查看审核与调整',{exact:true})).toHaveCount(0);
 await expect(page.getByText(/recovery 不足/)).toHaveCount(0);
 const active=page.locator(`[data-task-id="${activeId}"]`);
 await expect(active.locator('.paw-task-headmeta')).toHaveText('12:00–13:00');
 await expect(active.locator('.paw-task-headmeta').getByLabel('时段受保护')).toBeVisible();
 await expect(page.locator(`[data-task-id="${eveningId}"] .paw-task-headmeta`)).toHaveText('30m');
 await active.locator('.paw-task-summary').click();
 await expect(active.locator('.paw-task-copy-row button')).toHaveText(['安排／收尾','记录用时','复制资料']);
 await expect(active.locator('.paw-task-actions button')).toHaveText(['卡住','延后','移出排期','删除']);
 const records=page.getByRole('region',{name:'实际记录',exact:true});
 await expect(records.getByText('查看日期',{exact:true})).toHaveCount(0);
 await expect(records.getByLabel('实际记录日期')).toHaveValue(day());
 await expect(records.getByRole('heading',{name:'已做完的整理'})).toBeVisible();
 await expect(records.getByText('关联任务已完成')).toBeVisible();
 expect(await records.getByRole('heading',{name:'实际记录',exact:true}).evaluate(node=>node.closest('header')?.nextElementSibling?.contains(node))).toBe(false);
 const timeline=page.getByRole('region',{name:'全天时间轴'});
 const past=timeline.getByRole('button',{name:`计划：${longTitle}，00:00 至 00:30`,exact:true});
 await expect(past.getByText('待收尾',{exact:true})).toBeVisible();
 await expect(past.getByText('收尾或续一段')).toBeVisible();
 const current=timeline.getByRole('button',{name:/计划：下午阅读，/});
 await expect(current.getByText('当前计划',{exact:true})).toBeVisible();
 await expect(current.getByText('与其他安排重叠')).toBeVisible();
 await expect(timeline.getByText('现在 12:45',{exact:true})).toHaveCount(1);
 await expect(page.getByLabel('时间轴图例')).toHaveText('计划实际记录当前计划');
 await expect(page.getByText('进行中',{exact:true})).toHaveCount(0);
 await expect(page.getByText(/空闲/)).toHaveCount(0);
 const arrange=page.getByRole('button',{name:'安排任务时段',exact:true});
 expect((await arrange.boundingBox())!.height).toBeGreaterThanOrEqual(44);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.evaluate(()=>window.scrollTo(0,0));
 await page.screenshot({path:info.outputPath('today-refined-layout.png'),fullPage:true});
 await page.locator(`[data-task-id="${taskId}"]`).getByRole('button',{name:'标记完成',exact:true}).click();
 await expect(groups.locator('h3')).toHaveText(['下午','晚上','已完成']);
 await expect.poll(async()=>(await pool.query('select status from tasks where id=$1',[taskId])).rows[0].status).toBe('done');
 await page.reload();
 await expect(groups.locator('h3')).toHaveText(['下午','晚上','已完成']);
 await page.goto('/plan?view=week');
 await expect(page.getByRole('heading',{name:'恢复时间',exact:true})).toHaveCount(0);
 await expect(page.getByText('午休',{exact:true}).first()).toBeVisible();
 expect((await pool.query("select count(*) from time_blocks where workspace_id=$1 and kind='recovery'",[workspaceId])).rows[0].count).toBe('1');
});

test("desktop and mobile record, edit, reload, timeline, task completion and safe removal",async({page,isMobile},info)=>{
 await page.goto('/today');
 await expect(page.getByRole('heading',{name:'实际记录',exact:true})).toBeVisible();
 await expect(page.getByRole('heading',{name:'收工反馈'})).toHaveCount(0);
 await expect(page.getByText('这天还没有记录。可以补记一段，也可以留白。')).toBeVisible();
 const task=page.locator(`[data-task-id="${taskId}"]`);
 await task.locator('.paw-task-summary').click();
 await task.getByRole('button',{name:'记录用时',exact:true}).click();
 const dialog=page.getByRole('dialog');
 await expect(dialog.getByLabel('做了什么')).toHaveValue(longTitle);
 await dialog.getByLabel('开始时间',{exact:true}).fill(`${day()}T00:05`);
 await dialog.getByLabel('结束时间',{exact:true}).fill(`${day()}T00:25`);
 await dialog.getByLabel('时间是大致估计的').check();
 if(isMobile) await page.setViewportSize({width:320,height:740});
 await expect(dialog.getByRole('button',{name:'保存记录',exact:true})).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await expect(dialog.getByRole('button',{name:'保存记录',exact:true})).toBeInViewport();
 await page.screenshot({path:info.outputPath('record-editor.png')});
 await dialog.getByRole('button',{name:'保存记录',exact:true}).click();
 await expect(dialog).toHaveCount(0);
 const records=page.getByRole('region',{name:'实际记录',exact:true});
 await expect(records.getByRole('heading',{name:longTitle,exact:true})).toBeVisible();
 const timeline=page.getByRole('region',{name:'全天时间轴'});
 await expect(timeline.getByRole('button',{name:`实际记录：${longTitle}，00:05 至 00:25`,exact:true})).toBeVisible();
 await expect(timeline.getByRole('button',{name:`计划：${longTitle}，00:00 至 00:30`,exact:true})).toHaveCount(0);
 await page.reload();
 await expect(records.getByRole('heading',{name:longTitle,exact:true})).toBeVisible();
 const saved=await pool.query('select * from actual_records where workspace_id=$1',[workspaceId]);
 expect(saved.rows).toHaveLength(1);expect(saved.rows[0].approximate).toBe(true);
 let taskRow=(await pool.query('select status,scheduled_start from tasks where id=$1',[taskId])).rows[0];
 expect(taskRow.status).toBe('todo');expect(taskRow.scheduled_start.toISOString()).toBe(new Date(`${day()}T00:00:00+08:00`).toISOString());
 await records.getByRole('button',{name:`修改记录：${longTitle}`}).click();
 await dialog.getByText('查看记录时的计划',{exact:true}).click();
 await expect(dialog.getByText('00:00–00:30 · 预计 30 分钟')).toBeVisible();
 await dialog.getByLabel('结束时间',{exact:true}).fill(`${day()}T00:28`);
 await dialog.getByRole('button',{name:'保存记录',exact:true}).click();
 await expect(records.getByText(/23 分钟/)).toBeVisible();
 await task.getByRole('button',{name:'标记完成',exact:true}).click();
 await expect(records.getByText('关联任务已完成')).toBeVisible();
 expect((await pool.query('select count(*) from actual_records where workspace_id=$1',[workspaceId])).rows[0].count).toBe('1');
 if(isMobile) await page.setViewportSize({width:390,height:844});
 await page.evaluate(()=>window.scrollTo(0,0));
 await page.screenshot({path:info.outputPath('today-actual-records.png'),fullPage:true});
 await records.getByRole('button',{name:`修改记录：${longTitle}`}).click();
 await dialog.getByRole('button',{name:'移除记录',exact:true}).click();
 await dialog.getByRole('button',{name:'确认移除记录'}).click();
 await expect(records.getByText('这天还没有记录。可以补记一段，也可以留白。')).toBeVisible();
 expect((await pool.query('select deleted_at from actual_records where workspace_id=$1',[workspaceId])).rows[0].deleted_at).not.toBeNull();
});

test("readback failure locks uncertain edits and retries the same persisted record",async({page})=>{
 await page.goto('/today');
 await page.getByRole('button',{name:'记一段',exact:true}).click();
 const dialog=page.getByRole('dialog');
 await dialog.getByLabel('做了什么').fill('散步');
 await dialog.getByLabel('开始时间',{exact:true}).fill(`${day()}T00:05`);
 await dialog.getByLabel('结束时间',{exact:true}).fill(`${day()}T00:15`);
 let failed=false;
 await page.route('**/api/actual-records',async(route)=>{
  if(route.request().method()==='POST'&&!failed){failed=true;const response=await route.fetch();const data=await response.json();await route.fulfill({json:{...data,status:'applied_with_readback_error',readback:{verification:'failed'}}});}else await route.continue();
 });
 await dialog.getByRole('button',{name:'保存记录',exact:true}).click();
 await expect(dialog.getByText('结果尚未核对，暂时锁定输入。重试会核对同一条记录；也可关闭后重新读取。')).toBeVisible();
 await expect(dialog.getByLabel('做了什么')).toBeDisabled();
 await dialog.getByRole('button',{name:'保存记录',exact:true}).click();
 await expect(dialog).toHaveCount(0);
 expect((await pool.query('select count(*) from actual_records where workspace_id=$1',[workspaceId])).rows[0].count).toBe('1');
 // Closing an uncertain second save must also refresh from persistence, without a manual reload.
 failed=false;
 await page.getByRole('button',{name:'记一段',exact:true}).click();
 await dialog.getByLabel('做了什么').fill('喝水休息');
 await dialog.getByLabel('开始时间',{exact:true}).fill(`${day()}T00:15`);
 await dialog.getByLabel('结束时间',{exact:true}).fill(`${day()}T00:20`);
 await dialog.getByRole('button',{name:'保存记录',exact:true}).click();
 await expect(dialog.getByLabel('做了什么')).toBeDisabled();
 await dialog.getByRole('button',{name:'取消',exact:true}).click();
 await expect(page.getByRole('region',{name:'实际记录',exact:true}).getByRole('heading',{name:'喝水休息'})).toBeVisible();
 expect((await pool.query('select count(*) from actual_records where workspace_id=$1',[workspaceId])).rows[0].count).toBe('2');

});

test("overnight history and failed loading are not mistaken for no activity",async({page})=>{
 const previous=new Date(Date.parse(`${day()}T00:00:00+08:00`)-86400000);const yesterday=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(previous);
 await pool.query("insert into actual_records(workspace_id,title,starts_at,ends_at) values($1,'睡觉',$2,$3)",[workspaceId,`${yesterday}T23:00:00+08:00`,`${day()}T00:30:00+08:00`]);
 await page.goto('/today');const records=page.getByRole('region',{name:'实际记录',exact:true});
 await expect(records.getByText('23:00–次日 00:30 · 90 分钟')).toBeVisible();
 await records.getByLabel('实际记录日期').fill(yesterday);
 await expect(records.getByRole('heading',{name:'睡觉'})).toBeVisible();
 await page.route('**/api/actual-records?*',route=>route.fulfill({status:503,json:{error:'unavailable'}}));
 await records.getByLabel('实际记录日期').fill(day());
 await page.reload();
 await expect(records.getByText('实际记录暂时无法读取，请重试。')).toBeVisible();
 await expect(records.getByText('这天还没有记录。可以补记一段，也可以留白。')).toHaveCount(0);
 await page.unroute('**/api/actual-records?*');await records.getByRole('button',{name:'重试读取'}).click();
 await expect(records.getByRole('heading',{name:'睡觉'})).toBeVisible();
});

test('task picker only offers today tasks, including completed tasks, and preserves drafts', async ({page,isMobile},info) => {
 const plan=(await pool.query('select plan_id from tasks where id=$1',[taskId])).rows[0].plan_id;
 for(const date of ['2026-01-01','2036-01-01']) await pool.query("insert into tasks(workspace_id,plan_id,title,date,day_segment,estimated_minutes) values($1,$2,$3,$4,'morning',30)",[workspaceId,plan,`其他日期任务 ${date}`,date]);
 await pool.query("update tasks set status='done' where id=$1",[taskId]);
 await page.goto('/today');await page.getByRole('button',{name:'记一段',exact:true}).click();
 const dialog=page.getByRole('dialog');await dialog.getByLabel('做了什么').fill('保留真实记录');
 await dialog.getByLabel('开始时间',{exact:true}).fill(`${day()}T00:05`);await dialog.getByLabel('结束时间',{exact:true}).fill(`${day()}T00:20`);
 await dialog.getByRole('button',{name:'选择关联任务',exact:true}).click();
 await expect(dialog.getByText('仅显示今天安排的任务 · 包括今天已完成的任务')).toBeVisible();
 const results=dialog.locator('[aria-label="可关联任务"]');await expect(results.getByRole('button')).toHaveCount(1);
 await expect(results.getByText('今天 · 已完成')).toBeVisible();
 await dialog.getByLabel('搜索关联任务').fill('其他日期');await expect(results.getByRole('button')).toHaveCount(0);
 await expect(dialog.getByText('没有匹配的今日任务，试试其他关键词。')).toBeVisible();
 await dialog.getByLabel('搜索关联任务').fill('Gao');
 if(isMobile)await page.setViewportSize({width:320,height:740});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:info.outputPath('today-task-picker.png')});
 await results.getByRole('button').click();await expect(dialog.getByLabel('做了什么')).toHaveValue('保留真实记录');
 await dialog.getByRole('button',{name:'保存记录',exact:true}).click();await expect(dialog).toHaveCount(0);
 expect((await pool.query('select task_id from actual_records where workspace_id=$1',[workspaceId])).rows).toEqual([{task_id:taskId}]);
});
