import { test, expect } from "@playwright/test";
import { Pool } from "pg";
import { randomUUID, createHmac } from "node:crypto";
const url = process.env.DATABASE_URL ?? "";
if (!url.includes("pawplan_records_check") || !url.includes("127.0.0.1")) throw new Error("Requires isolated pawplan_records_check database");
const pool = new Pool({ connectionString: url });
const day = () => new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Shanghai", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
let w: string, plan: string, task: string;
test.beforeEach(async ({ context, page }) => {
 w = randomUUID(); plan = randomUUID(); task = randomUUID();
 await pool.query("insert into workspaces(id,name,password_hash) values($1,'assistant-ui-test','test')", [w]);
 await pool.query("insert into plans(id,workspace_id,title,start_date,end_date,status,baseline_snapshot) values($1,$2,'验收计划','2026-01-01','2036-12-31','active','{}')", [plan,w]);
 await pool.query("insert into tasks(id,workspace_id,plan_id,title,date,day_segment,estimated_minutes,energy_level) values($1,$2,$3,'Gao：核对第一节',$4,'morning',30,'low')", [task,w,plan,`${day()}T00:00:00+08:00`]);
 await context.addCookies([{name:'daily_progress_workspace',value:w+'.'+createHmac('sha256','test-secret').update(w).digest('base64url'),domain:'127.0.0.1',path:'/',httpOnly:true,sameSite:'Lax'}]);
 await page.route('**/api/onboarding',route=>route.fulfill({json:{completedCount:4,totalCount:4,nextStep:null,steps:[]}}));
});
test.afterEach(async () => { await pool.query('delete from workspaces where id=$1',[w]); });
test.afterAll(async () => { await pool.end(); });
async function seedReview() {
 const old = randomUUID(); const fresh = randomUUID();
 const row = {title:'MATH 3700',kind:'course',startsOn:'2026-10-01',endsOn:'2026-10-01',startTime:'14:30',endTime:'15:45',dayOfWeek:null,course:null,recurrence:null,notes:null,location:'教室 A'};
 for (const [id,label] of [[old,'十月日程'],[fresh,'十月日程 v2']]) await pool.query("insert into agent_patches(id,workspace_id,plan_id,scope_start,scope_end,reason,patch_json,created_by) values($1,$2,$3,'2026-10-01','2026-10-31','测试理由',$4,'claude')",[id,w,plan,JSON.stringify({operations:[{type:'import_timetable',source_label:label,rows:Array.from({length:27},(_,i)=>({...row,title:'课程 '+(i+1)})),reason:'用户提供的十月课程与会议清单。已核对日期、上课时间和地点；草稿仅用于审核，需要用户确认后再正式导入。'.repeat(3)}]})]);
 await pool.query("insert into agent_patch_reviews(workspace_id,patch_id,plan_id,accepted_operation_indexes,rejected_operation_indexes,skipped_json,conflict_json) values($1,$2,$3,'[]','[]',$4,$5)",[w,old,plan,JSON.stringify([{index:0,reason:'Timetable import overlaps existing blocks'}]),JSON.stringify([{index:0,reason:'Timetable import overlaps existing blocks',expected:{overlapCount:0},actual:{overlapCount:2,overlaps:[{title:'课程 1 与 已有课程 时间重叠'},{title:'课程 1 与 已有课程 时间重叠'}]}}])]);
 return {old,fresh};
}
test('Review import cards stay review-only while exposing concise and reversible details', async ({page,isMobile}, info) => {
 await seedReview(); await page.goto('/review');
 if(isMobile) await page.setViewportSize({width:320,height:740});
 await expect(page.locator('.paw-suggestion-card')).toHaveCount(2);
 const active=page.locator('[data-import-status="pending"]'); const old=page.locator('[data-import-status="blocked"]');
 await expect(active).toContainText('27 行 / 27 个时间块'); await expect(active).toContainText('尚未导入');
 await expect(old.locator('details').first()).not.toHaveAttribute('open','');
 await expect(page.getByText('Timetable import overlaps existing blocks',{exact:true})).toBeHidden();
 await active.getByRole('button',{name:'选择导入',exact:true}).click();
 await expect(active).toContainText('已选择导入 · 待提交');
 await expect(page.getByRole('button',{name:'提交并应用 1 项'})).toBeEnabled();
 await active.getByRole('button',{name:'撤回导入选择',exact:true}).click();
 await old.locator('summary').first().click();
 await expect(old.getByText('课程 1 与 已有课程 时间重叠',{exact:true})).toHaveCount(1);
 await old.locator('summary').first().click();
 await page.evaluate(()=>window.scrollTo(0,0)); await page.screenshot({path:info.outputPath('review-cards.png'),fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 expect((await pool.query('select count(*) from time_blocks where workspace_id=$1',[w])).rows[0].count).toBe('0');
});
test('calendar retains exact short durations and overlapping events with readable details',async({page,isMobile},info)=>{
 for(const [title,kind,start,end] of [['早间准备','routine','07:00','07:10'],['相邻短安排','routine','07:10','07:20'],['MATH 3700 · Big Data Computing — 模型、计算与实验设计','course','14:30','15:45'],['重叠讨论','meeting','14:40','15:10'],['晚间整理','routine','17:30','17:40']] as const) await pool.query('insert into time_blocks(workspace_id,title,kind,starts_at,ends_at) values($1,$2,$3,$4,$5)',[w,title,kind,`${day()}T${start}:00+08:00`,`${day()}T${end}:00+08:00`]);
 await page.goto(`/constraints?date=${day()}`);
 if(isMobile) await page.setViewportSize({width:320,height:740}); else await page.setViewportSize({width:1920,height:1080});
 await expect(page.getByRole('button',{name:/早间准备，07:00 至 07:10/}).first()).toBeVisible();
 const timetable=page.locator('section[aria-labelledby="timetable-heading"]');
 const short = isMobile ? page.getByRole('button',{name:/^早间准备，07:00 至 07:10/}) : page.getByRole('button',{name:/^查看短安排：早间准备/});
 expect((await short.boundingBox())!.height).toBeGreaterThanOrEqual(44);
 if(!isMobile) {
   expect((await timetable.boundingBox())!.width).toBeGreaterThan(1750);
   expect(await timetable.locator('[class*="desktopWeek"]').evaluate(node=>getComputedStyle(node).overflowY)).toBe('visible');
   expect((await timetable.getByRole('button',{name:/^早间准备，07:00 至 07:10/}).boundingBox())!.height).toBeCloseTo(10,0);
 } else await expect(page.getByRole('region',{name:/日程列表/}).getByText('与其他安排重叠')).toHaveCount(2);
 await short.click(); await expect(page.getByRole('dialog')).toContainText('07:10');
 await page.getByRole('button',{name:'关闭日程详情'}).click();
 await page.evaluate(()=>window.scrollTo(0,0)); await page.screenshot({path:info.outputPath('calendar.png'),fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('removed manual assistant entries stay absent while existing records and controls remain',async({page,isMobile},info)=>{
 const content={action:'save_continuation',task_id:task,progress:'保留已有进展',blockers:[],next_step:'下次核对第二节',evidence:[]};
 await pool.query("insert into continuation_records(workspace_id,task_id,kind,content) values($1,$2,'progress',$3)",[w,task,JSON.stringify(content)]);
 await pool.query("insert into actual_records(workspace_id,task_id,title,starts_at,ends_at) values($1,$2,'原有实际记录',$3,$4)",[w,task,`${day()}T09:00:00+08:00`,`${day()}T09:20:00+08:00`]);
 let assistantCalls=0;page.on('request',request=>{if(new URL(request.url()).pathname==='/api/assistant') assistantCalls++;});
 await page.goto('/today');if(isMobile)await page.setViewportSize({width:390,height:844});
 await expect(page.getByRole('region',{name:'当前与下一项计划'})).toBeVisible();
 await expect(page.getByRole('region',{name:'接着做',exact:true})).toHaveCount(0);
 for(const name of ['记录进展','帮我选下一步','计划与实际']) await expect(page.getByRole('button',{name,exact:true})).toHaveCount(0);
 const records=page.getByRole('region',{name:'实际记录',exact:true});
 await expect(records).toContainText('原有实际记录');
 await page.locator(`[data-task-id="${task}"] .paw-task-summary`).click();
 await expect(page.getByRole('button',{name:'记录进展',exact:true})).toHaveCount(0);
 await expect(page.getByRole('button',{name:'记录用时',exact:true})).toBeVisible();
 await expect(page.getByRole('button',{name:'安排／收尾',exact:true})).toBeVisible();
 await records.getByRole('button',{name:'记一段',exact:true}).click();
 const dialog=page.getByRole('dialog');await expect(dialog.getByLabel('做了什么')).toBeVisible();
 await dialog.getByRole('button',{name:'取消',exact:true}).click();await expect(dialog).toHaveCount(0);
 await page.screenshot({path:info.outputPath('today-without-manual-assistant.png'),fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 expect(assistantCalls).toBe(0);
 expect((await pool.query('select content from continuation_records where workspace_id=$1',[w])).rows).toEqual([{content}]);
 expect((await pool.query('select title from actual_records where workspace_id=$1',[w])).rows).toEqual([{title:'原有实际记录'}]);
});
